name: Deploy Code

on:
  push:
    branches: [main]

jobs:
  deploy-embeddings:
    name: Deploy to Embeddings Space
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Push Embeddings code to Hugging Face
        run: |
          git init
          git lfs install
          git lfs track "*.png" "*.jpg" "*.jpeg" "*.h5"
          git add .gitattributes
          git config user.name "Anesu Kafesu"
          git config user.email "a.kafesu@alustudent.com"
          git checkout -b main
          git remote add origin https://akafesu:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/akafesu/fourwalls-embeddings-api
          git add .
          git commit -m "Auto deploy Embeddings API"
          git push --force origin main
        working-directory: ./embeddings

  deploy-chat-api:
    name: Deploy to Chat Space
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Push Chat code to Hugging Face
        run: |
          git init
          git config user.name "Anesu Kafesu"
          git config user.email "a.kafesu@alustudent.com"
          git checkout -b main
          git remote add origin https://akafesu:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/akafesu/fourwalls-chat-api
          git add .
          git commit -m "Auto deploy Chat API"
          git push --force origin main
        working-directory: ./chat

  deploy-recommendations:
    name: Deploy to Recommendations Space
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Push Recommendations code to Hugging Face
        run: |
          git init
          git lfs install
          git lfs track "*.png" "*.jpg" "*.jpeg" "*.h5"
          git add .gitattributes
          git config user.name "Anesu Kafesu"
          git config user.email "a.kafesu@alustudent.com"
          git checkout -b main
          git remote add origin https://akafesu:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/akafesu/fourwalls-recommendations-api
          git add .
          git commit -m "Auto deploy Recommendations API"
          git push --force origin main
        working-directory: ./recommendations

  deploy-marketplace-functions:
    name: Deploy Marketplace Supabase functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
      
      - name: Deploy Supabase Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          npx supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
        working-directory: ./marketplace

  deploy-to-netlify:
    name: Deploy to Netlify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          npm install
          netlify deploy \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --prod \
            --dir=dist
        working-directory: ./marketplace
